name: 'Argocd apps edited in PR'
description: 'GitHub action to retrieve argocd app edited in a PR'
inputs:
  all_modified_files:
    description: 'From tj-actions/changed-files: Returns all changed files i.e. a combination of all added, copied, modified and renamed files (ACMR)'
    required: true
outputs:
  apps:
    description: 'The list of ArgoCD app with changes'
runs:
  using: 'node16'
  main: 'lib/index.js'
